# Generated by Django 4.2.23 on 2025-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_texttospeech'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttospeech',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts_audio/'),
        ),
    ]
