# Generated by Django 4.2.23 on 2025-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_texttospeech_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClonedVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('elevenlabs', 'ElevenLabs'), ('coqui', 'Coqui XTTS')], max_length=20)),
                ('sample_audio', models.FileField(blank=True, null=True, upload_to='voice_samples/')),
                ('external_voice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
